modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/SonarSonic/Flux-Networks/issues"
license="MIT"

[[mods]]
    modId="fluxnetworks"
    version="${version}"
    displayName="Flux Networks"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/flux-networks"
    authors="Sonar Sonic, BloCamLimb"
    description='''
    Wireless Energy Networks
    '''

[[dependencies.fluxnetworks]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="modernui"
    mandatory=false
    versionRange="[3.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="jei"
    mandatory=false
    versionRange="[14,)"
    ordering="NONE"
    side="BOTH"
